<%@ page contentType="text/html;charset=windows-1252"%>
<html>
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=windows-1252"/>
    <LINK href="<%=request.getContextPath()%>/css/StyleSheet.css" rel="stylesheet" type="text/css">
    <title>contact</title>
  </head>
  <body>
            <table border="1">
                    <tr>
                        <td>
                             <table width="100%" border="0" cellpadding="1" cellspacing="1">
                                                <tr>
                                                    <th width="20%" class="ColumnBackground"><div align="center">DEPARTMENT</div></th>
                                                    <th width="30%" class="ColumnBackground"><div align="center">CONTACT NO.</div></th>
                                                    <th width="50%" class="ColumnBackground"><div align="center">EMAIL-ID</div></th>
                                                </tr>
                                                <tr>
                                                    <td width="20%" class="TableData"><div align="center">IT</div></td>
                                                    <td width="30%" class="TableData">022-61437802/808</td>
                                                    <td width="50%" class="TableData">IT@CGTMSE.IN,SUPPORT@CGTMSE.IN</td>
                                                </tr>
                                                <tr>
                                                    <td width="20%" class="TableData"><div align="center">GUARANTEE</div></td>
                                                    <td width="30%" class="TableData">022-61437809/813/816</td>
                                                    <td width="50%" class="TableData">GF@CGTMSE.IN</td>
                                                </tr>
                                                <tr>
                                                    <td width="20%" class="TableData"><div align="center">NPA</div></td>
                                                    <td width="30%" class="TableData">022-61437804</td>
                                                    <td width="50%" class="TableData">CLAIM@CGTMSE.IN</td>
                                                </tr>
                                                <tr>
                                                    <td width="20%" class="TableData"><div align="center">CLAIM</div></td>
                                                    <td width="30%" class="TableData">022-61437806/814/815/821/822</td>
                                                    <td width="50%" class="TableData">CLAIM@CGTMSE.IN,CLAIMSSECTION@CGTMSE.IN</td>
                                                </tr>
                                                <tr>
                                                    <td width="20%" class="TableData"><div align="center">ASF</div></td>
                                                    <td width="30%" class="TableData">022-61437810</td>
                                                    <td width="50%" class="TableData">ASF@CGTMSE.IN</td>
                                                </tr>                                      
                                </table>
                            </td>
                        </tr>
                        <tr>
                            <td>
                            <table>
                                <tr>
                                <th class="TableData">Procedure for allocation of Annual Guarantee Fee (AGF)</th>
                                </tr>
                                <tr>
                                <td class="TableData">
                                         <b>Step 1:</b> Go to Payments and Receipts Module. 
                                    <br/><b>Step 2:</b> Select Allocate Payments through NEFT option and select Guarantee Fee. 
                                    <br/><b>Step 3:</b> Select DAN from the list (list of accounts where AGF payment is proposed now). 
                                    <br/><b>Step 4:</b> Check mark the Pay button and Save the changes (ignore cheque/D D No./Date) and note RP number generated by system. 
                                    <br/><b>Step 5:</b> On the same day, please remit AGF through NEFT/RTGS and ensure that RP number is mentioned in the remarks columns of NEFT/RTGS. 
                                    <br/><b>Step 6:</b> On the same day, please update UTR No. of NEFT/RTGS through RP -> Map RP with NEFT payment. 
                                    <br/><b>Step 7:</b> Got Reports and MIS module  Select  RP related report select GF Allocated Report. 
                                    <br/><b>Step 8:</b> Fill the details viz., Address of MLI etc. 
                                    <br/><b>Step 9:</b> Take the print out and forward to CGTMSE.
                                </td>
                                </tr>
                            </table>
                            </td>
                        </tr>
                        
         </table>
         
  </body>
</html>